version: '2'

services:
    payment:
        image: TAG_TO_REPLACE
        hostname: payment
        restart: always
        environment:
          - DT_CUSTOM_PROP=app=payment environment=dev
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        ports:
            - "8086:80"
networks:
    default:
        external:
            name: TO_REPLACE